package cl.consalud.poc;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(6a04121a395e950835cade57a32c9bf5)
 */
@org.kie.api.definition.type.Label(value = "cliente")
public class Clienyr  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "edad")
    @org.kie.api.definition.type.Position(value = 0)
    private int edad;
    
    @org.kie.api.definition.type.Label(value = "estadoCivil")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Character estadoCivil;
    
    @org.kie.api.definition.type.Label(value = "resultado")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Character resultado;

    public Clienyr() {
    }

    public Clienyr(int edad, java.lang.Character estadoCivil, java.lang.Character resultado) {
        this.edad = edad;
        this.estadoCivil = estadoCivil;
        this.resultado = resultado;
    }


    
    public int getEdad() {
        return this.edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }
    
    public java.lang.Character getEstadoCivil() {
        return this.estadoCivil;
    }

    public void setEstadoCivil(java.lang.Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    
    public java.lang.Character getResultado() {
        return this.resultado;
    }

    public void setResultado(java.lang.Character resultado) {
        this.resultado = resultado;
    }
}